# Generated by Django 5.2.8 on 2025-11-25 16:14

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category_type", models.CharField(max_length=100)),
                ("subcategory_type", models.CharField(blank=True, max_length=100)),
                ("attributes_schema", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "_category",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                (
                    "_subcategory",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                ("description", models.TextField(blank=True)),
                ("short_description", models.CharField(blank=True, max_length=500)),
                ("brand", models.CharField(max_length=100)),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("upc", models.CharField(blank=True, max_length=100)),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z]{3}$")
                        ],
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "stock_threshold",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("weight", models.FloatField(blank=True, null=True)),
                ("length", models.FloatField(blank=True, null=True)),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("origin_country", models.CharField(blank=True, max_length=54)),
                ("shipping_required", models.BooleanField(default=True)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("product_size", models.CharField(blank=True, max_length=50)),
                ("material", models.CharField(blank=True, max_length=50)),
                ("image_main", models.URLField(blank=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("rating_average", models.FloatField(default=0.0)),
                ("review_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attributes", models.JSONField(default=dict)),
                (
                    "variant_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.producttype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["_category"], name="catalog_pro__catego_3076da_idx"
                    ),
                    models.Index(
                        fields=["_category", "_subcategory"],
                        name="catalog_pro__catego_fd4bad_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["attributes"], name="catalog_pro_attribu_0f1f21_gin"
                    ),
                ],
            },
        ),
    ]
