# Generated by Django 5.2.8 on 2025-11-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="catalog_pro__catego_3076da_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="catalog_pro__catego_fd4bad_idx",
        ),
        migrations.RemoveField(
            model_name="product",
            name="_category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="_subcategory",
        ),
        migrations.AlterField(
            model_name="product",
            name="attributes",
            field=models.JSONField(
                default=dict,
                help_text="Product-specific attributes defined by the product type schema.",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="height",
            field=models.FloatField(
                blank=True,
                help_text="Height of the product in centimeters (cm).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.FloatField(
                blank=True,
                help_text="Length of the product in centimeters (cm).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_size",
            field=models.CharField(
                blank=True,
                help_text="Size of the product in inches (e.g., 12in, 5.5in).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                help_text="The type of product, which defines category, subcategory, and attributes.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.producttype",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                help_text="Stock Keeping Unit: a unique identifier for product. Used in our shop only.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="upc",
            field=models.CharField(
                blank=True,
                help_text="Universal Product Code: an optional global identifier for the product.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.FloatField(
                blank=True, help_text="Weight of the product in grams (g).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.FloatField(
                blank=True,
                help_text="Width of the product in centimeters (cm).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="attributes_schema",
            field=models.JSONField(
                default=dict,
                help_text="JSON schema defining the attributes for products.",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="category_type",
            field=models.CharField(
                help_text="Main category for products of this type.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="subcategory_type",
            field=models.CharField(
                blank=True, help_text="Optional subcategory.", max_length=100
            ),
        ),
    ]
