# Generated by Django 5.2.8 on 2025-12-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_product_catalog_pro__catego_3076da_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_on_sale",
            field=models.BooleanField(default=False),
        ),
    ]
